services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: BgPostNoticeGeneration_Container
    ports:
      - "5341:5341"          
    env_file::
      - ./backend/.env